language: python
python:
- '2.7'

before_install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt

install:
    - python setup.py install

script: 
- python setup.py sdist --format zip
- python run_tests.py --with-coverage --cover-package=cloudshell

after_success:
    coveralls